### ISSUE TITLE
TypeError - JSON serializable

### ISSUE THREAD

**Issue by fedelemantuano** [pystorm/pystorm#44]
Hi, 

I have the following error, and I can't control the value of `virustotal`. Is it possible catch the `TypeError` exception in this method?

```
2017-05-21 17:57:11,364 - pystorm.serializers.serializer - ERROR - Failed to send message: {u'command': u'emit', u'anchors': [u'1650007468780778799'], u'need_task_ids': False, u'tuple': [u'8d7f84c0bd2b0d5c5c7251357ba80d189930a18a77d16be0077dba3bdedd10c1_2725447558', {u'virustotal': {'error': SSLError(SSLEOFError(8, u'EOF occurred in violation of protocol (_ssl.c:590)'),)}}, False]}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pystorm/serializers/serializer.py", line 33, in send_message
    self.output_stream.write(self.serialize_dict(msg_dict))
  File "/usr/local/lib/python2.7/dist-packages/pystorm/serializers/json_serializer.py", line 93, in serialize_dict
    serialized = json.dumps(msg_dict, namedtuple_as_object=False)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/__init__.py", line 397, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/encoder.py", line 291, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/encoder.py", line 373, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/encoder.py", line 268, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: SSLError(SSLEOFError(8, u'EOF occurred in violation of protocol (_ssl.c:590)'),) is not JSON serializable
```

Why in [this code line](https://github.com/pystorm/pystorm/blob/master/pystorm/serializers/json_serializer.py#L93) you leave the default of `ensure_ascii` to `True` of `json.dumps` method?  I know that this is not my case.

Thanks

**Comment by dan-blanchard** [comment]
@fedelemantuano, it looks to me like you are trying to serialize an `SSLError`, which is not JSON serializable. You just need to convert it to a string on your end before you try to `emit` it.

**Comment by fedelemantuano** [comment]
Yes I know. But I can't know when this happens so I need to catch TypeError and fail the tuple. In these days I tried to do this. But the fail, doesn't call the fail in spout and the topology goes in asynchronous loop.
